package:
  name: tiktorch
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version %}
  {% endif %}

  version:
   {{tagged_version}}

source:
  git_url: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python -m pip install --no-deps --ignore-installed .
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}


requirements:
  build:
    - pip
    - python {{ python }}
  run:
    - h5py
    - python {{ python }}*
    - numpy {{ numpy }}*
    - pyyaml
    - paramiko
    - pyzmq
    - zeromq
    - pytorch {{ pytorch_version }}*
    - inferno {{ inferno_version }}*


test:
  imports:
    - tiktorch
